//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_CURSOS_HORARIOS_FUTURO
    {
        public int SCH_ID { get; set; }
        public int CUR_ID { get; set; }
        public string SCH_DIA { get; set; }
        public string SCH_HORA { get; set; }
    
        public virtual MAE_CURSOS MAE_CURSOS { get; set; }
    }
}
