//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_CURSOS_HORARIOS
    {
        public int SCH_ID { get; set; }
        public int CUR_ID { get; set; }
        public string SCH_DIA { get; set; }
        public string SCH_HORA { get; set; }
    
        public virtual MAE_CURSOS MAE_CURSOS { get; set; }
    }
}
