//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TUTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAE_TUTOR()
        {
            this.MAE_CURSOS_LANZAMIENTOS = new HashSet<MAE_CURSOS_LANZAMIENTOS>();
        }
    
        public int TUT_ID { get; set; }
        public string TUT_NOMBRES { get; set; }
        public string TUT_APELLIDOS { get; set; }
        public string TUT_FOTO { get; set; }
        public string TUT_EMAIL { get; set; }
        public string TUT_ACTIVO { get; set; }
        public byte[] FOTO { get; set; }
        public string TUT_TELEFONO { get; set; }
        public string TUT_CUR_GRATUITO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAE_CURSOS_LANZAMIENTOS> MAE_CURSOS_LANZAMIENTOS { get; set; }
    }
}
