//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_CURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAE_CURSOS()
        {
            this.MAE_CURSOS_HORARIOS = new HashSet<MAE_CURSOS_HORARIOS>();
            this.MAE_CURSOS_LANZAMIENTOS = new HashSet<MAE_CURSOS_LANZAMIENTOS>();
            this.MAE_CURSOS_PUNTUACION = new HashSet<MAE_CURSOS_PUNTUACION>();
            this.MKT_DOCENTE_CURSO = new HashSet<MKT_DOCENTE_CURSO>();
            this.SEG_CURSOS_USUARIOS_LINKS = new HashSet<SEG_CURSOS_USUARIOS_LINKS>();
            this.SEG_USUARIOS_LINKS = new HashSet<SEG_USUARIOS_LINKS>();
            this.MAE_CURSOS_HORARIOS_FUTURO = new HashSet<MAE_CURSOS_HORARIOS_FUTURO>();
        }
    
        public int CUR_ID { get; set; }
        public string CUR_NOMBRE { get; set; }
        public string CUR_DESCRIPCION { get; set; }
        public string CUR_CERTIFICACION { get; set; }
        public string CUR_RESULTADOS { get; set; }
        public Nullable<decimal> CUR_PRECIO { get; set; }
        public string CUR_ACTIVO { get; set; }
        public string CUR_IMAGEN { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<int> CAT_ID { get; set; }
        public string CUR_ID_ENCRIPTADO { get; set; }
    
        public virtual MAE_CATEGORIAS MAE_CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAE_CURSOS_HORARIOS> MAE_CURSOS_HORARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAE_CURSOS_LANZAMIENTOS> MAE_CURSOS_LANZAMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAE_CURSOS_PUNTUACION> MAE_CURSOS_PUNTUACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MKT_DOCENTE_CURSO> MKT_DOCENTE_CURSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_CURSOS_USUARIOS_LINKS> SEG_CURSOS_USUARIOS_LINKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_USUARIOS_LINKS> SEG_USUARIOS_LINKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAE_CURSOS_HORARIOS_FUTURO> MAE_CURSOS_HORARIOS_FUTURO { get; set; }
    }
}
