//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_CURSOS_PUNTUACION
    {
        public int PUN_ID { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public Nullable<int> CUR_ID { get; set; }
        public Nullable<decimal> PUN_VALOR { get; set; }
    
        public virtual MKT_DOCENTES MKT_DOCENTES { get; set; }
        public virtual MAE_CURSOS MAE_CURSOS { get; set; }
    }
}
