//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TUTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAE_TUTOR()
        {
            this.MAE_CURSOS_LANZAMIENTOS = new HashSet<MAE_CURSOS_LANZAMIENTOS>();
        }
    
        public int TUT_ID { get; set; }
        public string TUT_NOMBRES { get; set; }
        public string TUT_APELLIDOS { get; set; }
        public string TUT_FOTO { get; set; }
        public string TUT_EMAIL { get; set; }
        public string TUT_ACTIVO { get; set; }
        public byte[] FOTO { get; set; }
        public string TUT_TELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAE_CURSOS_LANZAMIENTOS> MAE_CURSOS_LANZAMIENTOS { get; set; }
    }
}
