//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MKT_DOCENTE_CURSO
    {
        public int ID { get; set; }
        public int DOC_ID { get; set; }
        public int LAN_ID { get; set; }
        public int MKT_ID { get; set; }
        public Nullable<System.DateTime> DCU_FEC { get; set; }
        public int CUR_ID { get; set; }
        public Nullable<System.DateTime> DCU_FEC_MOD_LAST { get; set; }
        public Nullable<int> DCU_CANT_MOD { get; set; }
        public int LAN_NUM_SEMANA { get; set; }
    
        public virtual MKT_DOCENTES MKT_DOCENTES { get; set; }
        public virtual SEG_USUARIOS SEG_USUARIOS { get; set; }
        public virtual MAE_CURSOS_LANZAMIENTOS MAE_CURSOS_LANZAMIENTOS { get; set; }
        public virtual MAE_CURSOS MAE_CURSOS { get; set; }
    }
}
