//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MKT_DOCENTES
    {
        public int DOC_ID { get; set; }
        public string DOC_NOMBRES { get; set; }
        public string DOC_NICK { get; set; }
        public string DOC_APELLIDOS { get; set; }
        public string DOC_DNI { get; set; }
        public string DOC_CELULAR { get; set; }
        public string DOC_EMAIL { get; set; }
        public string DOC_REGION { get; set; }
        public string DOC_SIT_LAB { get; set; }
        public string DOC_CARGO { get; set; }
        public string DOC_NIVEL { get; set; }
        public string DOC_CONTRASENA { get; set; }
        public string DOC_DISPOSITIVO { get; set; }
    }
}
