//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MKT_DOCENTE_CURSO
    {
        public int DOC_ID { get; set; }
        public int LAN_ID { get; set; }
        public Nullable<int> MKT_ID { get; set; }
        public Nullable<System.DateTime> DCU_FEC { get; set; }
    
        public virtual MAE_CURSOS_LANZAMIENTOS MAE_CURSOS_LANZAMIENTOS { get; set; }
        public virtual SEG_USUARIOS SEG_USUARIOS { get; set; }
        public virtual MKT_DOCENTES MKT_DOCENTES { get; set; }
    }
}
