//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_USUARIOS_LINKS
    {
        public int LNK_ID { get; set; }
        public int USU_ID { get; set; }
        public int CUR_ID { get; set; }
        public int LAN_ID { get; set; }
        public string USU_LINK { get; set; }
        public string LNK_ACTIVO { get; set; }
        public string USU_LINK_CORTO { get; set; }
    }
}
