//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_USUARIOS_LINKS
    {
        public int LNK_ID { get; set; }
        public int USU_ID { get; set; }
        public int CUR_ID { get; set; }
        public int LAN_ID { get; set; }
        public string USU_LINK { get; set; }
        public string LNK_ACTIVO { get; set; }
        public string USU_LINK_CORTO { get; set; }
    
        public virtual SEG_USUARIOS SEG_USUARIOS { get; set; }
        public virtual MAE_CURSOS MAE_CURSOS { get; set; }
        public virtual MAE_CURSOS_LANZAMIENTOS MAE_CURSOS_LANZAMIENTOS { get; set; }
    }
}
