//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMKTDocenteCurso
    {
        public int DOC_ID { get; set; }
        public int LAN_ID { get; set; }
        public int MKT_ID { get; set; }
        public string DOC_NOMBRES { get; set; }
        public string DOC_APELLIDOS { get; set; }
        public string DOC_CELULAR { get; set; }
        public string DOC_EMAIL { get; set; }
        public Nullable<System.DateTime> DCU_FEC { get; set; }
        public int CUR_ID { get; set; }
        public Nullable<System.DateTime> LAN_FEC_CAPACITACION { get; set; }
        public string CUR_DESCRIPCION { get; set; }
        public Nullable<System.DateTime> fecha_filtro { get; set; }
    }
}
