//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMKTDocenteCurso
    {
        public int DOC_ID { get; set; }
        public int LAN_ID { get; set; }
        public int MKT_ID { get; set; }
        public string DOC_NOMBRES { get; set; }
        public string DOC_APELLIDOS { get; set; }
        public string DOC_CELULAR { get; set; }
        public string DOC_EMAIL { get; set; }
        public Nullable<System.DateTime> DCU_FEC { get; set; }
        public int CUR_ID { get; set; }
        public Nullable<System.DateTime> LAN_FEC_CAPACITACION { get; set; }
        public string CUR_DESCRIPCION { get; set; }
    }
}
